In [1]:
from gtts import gTTS
import torchaudio
import torch
import math

from millionbaht.handler import _transform_strip, _transform_volume

In [2]:
xx = gTTS("สวัสดีครับ")

In [3]:
xx.save("hello.wav")

In [4]:
x, sr = torchaudio.load("hello.wav")

In [5]:
y, sry = torchaudio.load("../dl/songs/gPxlYAqqlbk.mp4")

In [6]:
y, sry = _transform_volume(y, sry)

[2024-02-01 00:21:46,788] [INFO    ] millionbaht.handler: _transform_volume Input: torch.Size([2, 19337216])
[2024-02-01 00:21:47,531] [INFO    ] millionbaht.handler: _transform_volume Output: torch.Size([2, 19337216])


In [7]:
yy, sry = _transform_strip(y, sry)

[2024-02-01 00:21:47,540] [INFO    ] millionbaht.handler: _transform_strip Input: torch.Size([2, 19337216])
[2024-02-01 00:21:47,584] [INFO    ] millionbaht.handler: _transform_strip Output: torch.Size([2, 19337216])


In [30]:
math.ceil(N / db_frames) * db_frames

19342260

In [40]:
N = y.shape[-1]
db_frames = round(0.2 * sry)
yy = y.reshape(-1, N).mean(dim=-2)
# yy = torch.nn.functional.pad(yy, (0, math.ceil(N / db_frames) * db_frames - N))
# yy = yy.reshape(-1, db_frames)
yy = yy.unfold(-1, db_frames, db_frames // 2)

In [41]:
((yy.max(dim=-1).values - yy.min(dim=-1).values)V / math.sqrt(8)).log10() * 20

tensor([-52.4771, -19.7382, -15.5709,  ..., -37.9007, -43.4563, -44.7401])

In [10]:
yy[..., 0], y[..., 0]

(tensor([0., 0.]), tensor([0., 0.]))

In [16]:
torchaudio.functional.loudness(x, sr)

tensor(-19.5536)

In [19]:
torchaudio.functional.loudness(y, sry)

tensor(-8.6007)

In [24]:
kernel = torch.ones((1, 2, 1000))
yyy = torch.nn.functional.conv1d(y, kernel, padding="same")

In [25]:
yyy

tensor([[-2.3515e-06, -3.6842e-07,  2.6570e-06,  ...,  6.8440e-04,
          6.2686e-04,  5.9338e-04]])